### ISSUE TITLE
Zotero-inspire 分类不正确

### ISSUE THREAD

**Issue by fkguo** [zotero-chinese/zotero-plugins#108]
分类应该是 `条目元数据`，而不是`开发者工具`，名称是 `zotero-inspire`，不是 `zotero-inspire-dev`。

**Comment by northword** [comment]
名称是从 XPI 中获取的，当插件支持 Zotero 7 时，以 manifest.json 中的为准，否则以 install.rdf 中的为准。

**Comment by northword** [comment]
https://github.com/fkguo/zotero-inspire/blob/dev/package.json#L6C18-L6C39

此行应为 `zotero-inspire` 或 `Zotero INSPIRE Metadata Updater`

**Comment by fkguo** [comment]
> https://github.com/fkguo/zotero-inspire/blob/dev/package.json#L6C18-L6C39
> 
> 此行应为 `zotero-inspire` 或 `Zotero INSPIRE Metadata Updater`

已改为 `zotero-inspire`

**Comment by fkguo** [comment]
> 你好，是 addonsName 这个属性的值。在构建时，这个值会填充到 manifest.json 的 name 属性，成为插件名。
> 
> package.json 中的 name 属性在构建时是作为 xpi 名使用的。
> 
> 修改后需要一次新的发布，以使用新的插件名发布。

多谢，已修正
