### ISSUE TITLE
citation插件，在mac平台的zotero 7 上无法使用应用功能

### ISSUE THREAD

**Issue by JERRY-CLOIN** [zotero-chinese/zotero-plugins#133]
citation插件，在mac平台的zotero 7上无法使用应用功能

**Comment by northword** [comment]
对于插件的功能问题，你应向插件开发者反馈。

**Comment by JERRY-CLOIN** [comment]
不好意思，我只是想求助一下，应该不是插件的问题，只是我的设置的问题


发件人: Northword ***@***.***>
日期: 星期日, 2024年9月22日 11:58
收件人: zotero-chinese/zotero-plugins ***@***.***>
抄送: JERRY-CLOIN ***@***.***>, Author ***@***.***>
主题: Re: [zotero-chinese/zotero-plugins] citation插件，在mac平台的zotero 7 上无法使用应用功能 (Issue #133)

对于插件的功能问题，你应向插件开发者反馈。

―

**Comment by northword** [comment]
可以描述一下是哪方面不能用，有没有什么报错信息呢，目前的描述没办法判断出可能是哪里的问题。

**Comment by JERRY-CLOIN** [comment]
就是我安装插件之后，可以打开引用列，当时我在我的论文中引用之后，引用列上没有任何显示。插件版本0.4.4，软件版 7.0

**Comment by JERRY-CLOIN** [comment]
![WechatIMG441](https://github.com/user-attachments/assets/41f68cbb-812c-4fe5-9426-b5f4f6806814)
有引用列，当时空白，有打开word 并refresh过

**Comment by northword** [comment]
这看起来是 bug，可以去 https://github.com/MuiseDestiny/zotero-citation 反馈一下，看插件开发者怎么说。

**Comment by JERRY-CLOIN** [comment]
![image](https://github.com/user-attachments/assets/1a4a1d6a-2560-4d6b-8334-1049616e7c74)
有人已经说了哈哈，但是开发者还没回复
