### ISSUE TITLE
ZotFile

### ISSUE THREAD

**Issue by qkwang98** [zotero-chinese/zotero-plugins#135]
我的同步是基于[ZotFile]插件构建的,但是他并不支持Zotero7.

**Comment by northword** [comment]
这里仅接收插件收录相关的问题。

对于你的问题，可以尝试 [Attager 插件](https://zotero-chinese.com/plugins/#search=Zotero+Attanger)，[社区博文](https://zotero-chinese.com/blog/posts/hello-zotero-7#%E6%9B%B4%E6%96%B0%E5%90%8E%E6%8F%92%E4%BB%B6%E5%8F%AF%E4%BB%A5%E9%80%82%E9%85%8D%E5%90%97) 里有提到。

**Comment by qkwang98** [comment]
惠书敬悉，迟复为歉！Thank you. Your email is received and will be handled  as soon as possible.——汪棋凯
