### ISSUE TITLE
对插件列表添加标签

### ISSUE THREAD

**Issue by northword** [zotero-chinese/zotero-plugins#18]
针对插件功能添加标签以筛选，标签可参考官方插件列表页面：https://www.zotero.org/support/plugins

- 条目元数据 Item Metadata Import
- 附件管理 Attachment File Management
- Zotero Reports
- 界面交互 Interface Tools
- Library Analysis/Visualization
- 3rd Integration
- Word Processor and Writing Integration
- Developer Tools

标签应是写在 types 里的，不应任意定义。

标签存储可能用 enum 更好？

**Comment by northword** [comment]
我觉得行，就是网页可能也得跟着优化，并且需要支持多标签条件筛选，否则标签的意义就不大了

**Comment by l0o0** [comment]
如果更新复杂的搜索，标签和卡片，我们这种简单的md静态文件站，能否支持这些复杂的功能

**Comment by northword** [comment]
要支持这些，肯定是咱们自己写 vue 应用或 react 应用了。
