### ISSUE TITLE
表格改为卡片

### ISSUE THREAD

**Issue by northword** [zotero-chinese/zotero-plugins#20]
效果：https://docusaurus.io/zh-CN/showcase
源码：https://github.com/facebook/docusaurus/tree/main/website/src/pages/showcase
数据：https://github.com/facebook/docusaurus/blob/main/website/src/data/users.tsx

这样也许可以更好的实现标签筛选、下载量/星标 排序

**Comment by volatile-static** [comment]
没有预览图，不适合做卡片

**Comment by northword** [comment]
> 没有预览图，不适合做卡片

卡片其实也可以没图，实在不行和 PKMer 那边的一样，用 name 自动生成图片也可（他们好像是在后端生成图片，但是这个完全可以在前端完成

或者有其他的展示方式也可以实现的话也可

**Comment by northword** [comment]
话说我其实一直在考虑做这个的必要性，毕竟 @windingwind 说了官方要做，只是 Z 从来不在社区给一个路线图；包括插件商店插件也是。

官方做了的话，会不会类似 ob 那边一样有部分插件不想/无法上架官方的

**Comment by volatile-static** [comment]
综上所述，我觉得咱们先不要做卡片

**Comment by l0o0** [comment]
预览图，是不是可以直接使用插件的图标，都在 XPI 里
