### ISSUE TITLE
[Bug] 正确处理没有符合条件的XPI的release

### ISSUE THREAD

**Issue by northword** [zotero-chinese/zotero-plugins#25]
部分开发者创建的发布可能由于一些原因，未能包含正确的符合条件的 XPI 文件，导致脚本运行出错，例如

![image](https://github.com/zotero-chinese/zotero-plugins/assets/44738481/67f2e70a-ed78-45e7-aad5-1807f01dc45d)

我们可以有以下几种方案：

- 跳过
- 跳过，向对应仓库或本仓库 open issue
- 获取前一版本
- 获取前一版本，向对应仓库或本仓库 open issue

**Comment by volatile-static** [comment]
先合并缓解一下燃眉之急

**Comment by volatile-static** [comment]
先别关，之后要不再改成采用前一版本？

**Comment by northword** [comment]
> 先别关，之后要不再改成采用前一版本？

也可以噻
