### ISSUE TITLE
文件抓取名称不全

### ISSUE THREAD

**Issue by LIUHAITAO-CH** [zotero-chinese/zotero-plugins#60]
![image](https://github.com/zotero-chinese/zotero-plugins/assets/64388319/0c708630-3a97-4a53-ac2c-e0c237171e9b)
请问这个我目前是右击pdf文件，Rename file from parent matadata，但是总是显示不全，这个该怎么解决？感谢

**Comment by northword** [comment]
Zotero 7 参考 https://www.zotero.org/support/file_renaming `truncate`

---

此 Issue 将被转移至 discussion
