### ISSUE TITLE
ZoteroPreview（预览style引用）更新7的版本了

### ISSUE THREAD

**Issue by crazyi** [zotero-chinese/zotero-plugins#85]
插件地址：[ZoteroPreview](https://github.com/dcartertod/zotero-plugins)

**Comment by northword** [comment]
该仓库在一个仓库中发布了多个的插件，与常见的 Zotero 插件发布方式有较大差异，且不符合常见的 momorepo 方式，脚本尚无法处理这种情况。

PR welcome.

**Comment by northword** [comment]
鉴于 Zotero 7 beta 已经集成该插件的主要功能，同时考虑到本仓库脚本尚未支持非标单体仓库，故此插件可以放弃收录。

如果您认为有必要收录此插件，PR welcome。
